// A short capability deck: dark cover, content slide with cards and a table, dark close.
//   node 03_deck.js
const pptx = require("pptxgenjs");
const kit = require("../scripts/deck_kit.js");

const p = new pptx(); p.layout = "LAYOUT_WIDE";
const k = kit.bind(p, { logo: "../assets/logo/ink.png", logoDark: "../assets/logo/white.png" });
const t = k.t;

k.cover({
  kicker: "PLATFORM ENGINEERING",
  title: "The capability,\nin one deck",
  sub: "Covers carry the wordmark reversed out of the dark ground; content slides carry the ink version. One source file, three tints, generated by brand_logo.py.",
});

const s = k.slide({
  kicker: "THE PLATFORM",
  title: "Four functions, one control plane",
  sub: "Cards for shape, a table for detail, a band for the argument.",
});
[["Discover", "Inventory, dependency and cost across every account and region."],
 ["Secure", "Configuration and patch posture, scored against your own control set."],
 ["Operate", "Alert to root cause to remediation, with the resolution kept as memory."],
 ["Prove", "Evidence an auditor accepts, with the query behind every number."]]
  .forEach(([title, body], i) => k.card(s, 0.55 + i * 3.13, 1.35, 2.95, 1.5, title, body, { ts: 13 }));

const bottom = k.grid(s, 0.55, 3.1, [3.0, 4.6, 4.63], ["Capability", "What it needs", "State"], [
  ["Inventory and cost", "Read-only role per account", { tag: "LIVE", k: "ok" }],
  ["Posture scoring", "The same role, no write access", { tag: "LIVE", k: "ok" }],
  ["Auto-remediation", "A named, revocable action grant", { tag: "OPT-IN", k: "warn" }],
  ["Provisioning", "A repository and a ticket project", { tag: "ROADMAP", k: "warn" }],
], { boldFirst: true });

k.band(s, bottom + 0.3, "WHY BLOCKS RETURN THEIR BOTTOM EDGE",
  "grid(), card(), band() and steps() all return the y they finished at. Stack from that value instead of guessing the next one — it is the difference between a deck that survives an edit and one that quietly overlaps.");
k.foot(s, "Every value in the kit is inches on a 13.333 x 7.5 slide.");

const c = k.slide({ kicker: "COMPARING TWO OPTIONS", title: "Same spine, different components",
  sub: "When pitching option A against option B, keep the row structure identical so the customer can diff them." });
k.versus(c, 1.35,
  { t: "Self-hosted", b: ["You own the upgrade path and the capacity", "No per-request charge",
      "Portable — the exit is a container image", "A floor cost that does not scale to zero"] },
  { t: "Managed", b: ["The provider owns failover and patching", "Metered, scales to zero",
      "Exit is a data export, not a component", "Region and quota become dependencies"] });
k.band(c, 4.35, "THE RULE",
  "Differences should come from the components, not from the layout. Same rows, same numbered path, same trade-off line on both.");
k.save("out/03-deck.pptx");
